version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./src/DeviceManagementService.Api/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DevicesDb=Server=sqlserver,1433;Database=DevicesDb;User=sa;Password=SaStr0ng!Pass;TrustServerCertificate=True;
    ports:
      - "8080:8080"
      - "8081:8081"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: devices_sql
    user: root
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SaStr0ng!Pass"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sql_data: